### PR TITLE
Upgrade crc32cer (1.2.6) and snappyer (0.1.8)

### PR DESCRIPTION
**Pull request by zmstone**

### CODE REVIEW

**Review by mikpe — APPROVED** [review]

**Comment by zmstone** [comment]
sorry, this port_compiler thing is a huge mess.
solve one problem only to find another cropping up.

**Comment by jamesmacfie** [comment]
@zmstone What sort of issues are you having here? Not having this PR merged means consumers of this library cannot upgrade to OTP 23.

**Comment by zmstone** [comment]
> @zmstone What sort of issues are you having here? Not having this PR merged means consumers of this library cannot upgrade to OTP 23.

true. Prepare for OTP 23

**Comment by k32** [comment]
Sorry, I overlooked this PR while being on a break. New kafka_protocol is published on hex.

**Pull request merged**
