### PR TITLE
Do not reuse the same timeout during connection timeout

### PR DESCRIPTION
**Pull request by enidgjoleka**
Hi,

This PR tries to address two points:
* kpro_connection:start/3 spawns a new process which calls init/4. This fun was using the same connection_timeout during different phases of establishing the connection. 
This PR tries to use the "remaining timeout" in the different phases.
* kpro_brokers:discover_partition_leader/4 was calling kpro_lib:ok_pipe/1 without a timeout. It is true that now there is only one function that does network calls, kpro_connection:request_sync/3 but better be safe.

Please let me know if I missed something!

### CODE REVIEW

**Comment by enidgjoleka** [comment]
There is a failing test case which I am not sure is related to my change:

```
in call from kpro_txn_tests:test_txn_produce_2/2 (/home/travis/build/klarna/kafka_protocol/test/kpro_txn_tests.erl, line 164)
**error:{badmatch,{error,[{<<"test-topic">>,0,concurrent_transactions}]}}
  output:<<"">>
```

**Comment by k32** [comment]
Could you please explain in more detail what you want to achieve?

Timeout parameter is normally interpreted as "max network latency we want to tolerate", which is a pretty reasonable when dealing with the distributed system. Yes, during establishing connection in can be multiplied by number of steps we need to do _internally_, but that's kept as an internal implementation detail.

Now with the new deadline approach, one can set a deadline for connecting, but one has to know how many round-trips will be internally inside kafka_protocol in order to adjust this value for latency. If more round-trips are added to the handshake, then deadline can expire midway, which something we don't want. So perhaps connection deadline is better handled on the upper layers.

**Comment by enidgjoleka** [comment]
All the tests pass in both in OTP-21/OTP-22 in my local machine and I can not seem to reproduce this test failure.

It would be nice if I could get some traction on this PR.

**Comment by zmstone** [comment]
why isn't this merged yet.

**Comment by enidgjoleka** [comment]
@zmstone to be honest I don't know, maybe because there is a failing test case.

**Comment by robertoaloi** [comment]
I think @enidgjoleka is correct:

```
module 'kpro_txn_tests'
  kpro_txn_tests: txn_produce_test...[2.297 s] ok
  kpro_txn_tests: txn_fetch_produce_test...[0.126 s] ok
  kpro_txn_tests: txn_produce_2_tx_test...*failed*
in function kpro_txn_tests:'-test_txn_produce_2/2-fun-2-'/6 (/home/travis/build/klarna/kafka_protocol/test/kpro_txn_tests.erl, line 155)
in call from kpro_txn_tests:test_txn_produce_2/2 (/home/travis/build/klarna/kafka_protocol/test/kpro_txn_tests.erl, line 164)
in call from eunit_test:'-mf_wrapper/2-fun-0-'/2 (eunit_test.erl, line 273)
in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 510)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 335)
in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 493)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 435)
**error:{badmatch,{error,[{<<"test-topic">>,0,concurrent_transactions}]}}
  output:<<"">>
  [done in 2.540 s]
=======================================================
  Failed: 1.  Skipped: 0.  Passed: 55.
===> Error running tests
Makefile:39: recipe for target 'eunit' failed
make: *** [eunit] Error 1
```

**Comment by zmstone** [comment]
likely caused by inter test case race condition.
will follow up with another issue which should not be a blocker for this PR.

**Pull request merged**
