### PR TITLE
generate kafka.bnf from kafka client code

### PR DESCRIPTION
**Pull request by id**
@zmstone let me know what do you think about this

### CODE REVIEW

**Comment by zmstone** [comment]
brilliant! PR the new class to kafka?
They have a `toHtml`, why not a `toText` to make everyone else's life easier.

**Comment by id** [comment]
Good idea, will do later today.

**Comment by codesnik** [comment]
So, I've been trying to finish that PR, with a goal to support kafka 0.10.0+ versioned API in `brod` and streamline updating `kafka_protocol` in future. Some observations so far:

There's unwielding amount of records with the same name but different structure in generated code. Previously clashes were resolved by hand, with records named like `#kpro_OCReqV2Topic` and keys like `oCReqV2Partition_L`, but this won't work for automated export of 'BNF' from  [apache/kafka](https://github.com/apache/kafka). Naive shortening would fail on `LeaveGroupRequest` and `ListGroupsRequest`, for example. With almost identical subrecords in every version of each request, we probably need to prefix every subrecord name. Like this:

```erl
-record( kpro_MetadataResponseV0, {brokers, topicMetadata}).
-record( kpro_MetadataResponseV0_Broker, {nodeId, host, port}).
-record( kpro_MetadataResponseV0_TopicMetadata, {topicErrorCode, topic, partitionMetadata}).
-record( kpro_MetadataResponseV0_PartitionMetadata, {partitionErrorCode, partitionId, leader, replicas, isr}).

-record( kpro_MetadataResponseV2, {brokers, clusterId, controllerId, topicMetadata}).
-record( kpro_MetadataResponseV2_Broker, {nodeId, host, port, rack}).
-record( kpro_MetadataResponseV2_TopicMetadata, {topicErrorCode, topic, isInternal, partitionMetadata}).
-record( kpro_MetadataResponseV2_PartitionMetadata, {partitionErrorCode, partitionId, leader, replicas, isr}).
```

Btw, while we're at this and will have to rename things in brod anyway, and as original BNF is using under_score instead of camelCase, I'd like to rename everything in idiomatic erlang style. What do you think? Something like this:

```erl
-record( kpro_metadata_response_v2, {brokers, cluster_id, controller_id, topic_metadata}).
-record( kpro_metadata_response_v2_broker, {node_id, host, port, rack}).
-record( kpro_metadata_response_v2_topic_metadata, {topic_error_code, topic, is_internal, partition_metadata}).
-record( kpro_metadata_response_v2_partition_metadata, {partition_error_code, partition_id, leader, replicas, isr}).
```

anyway, `#kpro_MetadataResponseV0_PartitionMetadata` and `#kpro_MetadataResponseV2_PartitionMetadata` have the same structure between versions, but `..TopicMetadata..` is changing between v1 and v2. Having different versioning for subrecords is not an option, I think, but using the same versioning as the parent record would be quite painful/verbose to construct and match in brod.

But structs "evolve" quite slow and conservatively. I made a small repository https://github.com/codesnik/kafka_structs_versions , `git log -p --color-words` on it is quite illustrative.

What if I autogenerate "union" records for every possible request and response in a particular API endpoint, with `undefined` for deprecated or unused fields? A bit too explicit pseudocode:

```erl
-record( kpro_metadata_response, {brokers, cluster_id=undefined, controller_id=undefined, topic_metadata}).
-record( kpro_metadata_response_broker, {node_id, host, port, rack=undefined}).
-record( kpro_metadata_response_topic_metadata, {topic_error_code, topic, is_internal=undefined, partition_metadata}).
-record( kpro_metadata_response_partition_metadata, {partition_error_code, partition_id, leader, replicas, isr}).
```

then, `encode` function would also get `Version` argument to delegate encoding of the record to a proper encoder, and will also pass that version to subrecord encoders. Actual Version range could be  restricted in brod by ApiVersions handshake response and further guessed by matching on defined parameter list. This probably would hurt static analysis, though I don't know if and how you use it in brod. I don't know if I'm being clear enough, but any comments for that?

miscelaneous:

We can probably use 2 or 3 bits more from correlation_id for response version in addition to 5 bits for API number. Different brokers could have different kafka versions on them even in one cluster, so it's probably the easiest solution.

There's `nullable_string` type now in BNF. Current `kpro:str()` mapped to `string` BNF type accepts `undefined` and dumps -1 as the size, but only `nullable_string` should be able to accept `undefined`, according to kafka sources. Should I just alias `nullable_string` to `kpro:str()`, or should I define a new type? Restricting `string` could cause sudden runtime errors on message serialization. Or not.

**Comment by zmstone** [comment]
Thanks for the hard work!
Replying the easy ones first:
1. camelCase was derived from 0.8/0.9 specs, I'm totally for snake_case in new version
2. I don't remember if there is a case where we MUST use a null, if not, we can produce ONLY empty strings when it's 'undefined' for example.
3. I once ran dialyzer check on brod, but never succeeded making it 100% happy. But if there is a much nicer solution will less nicer static type info, don't get your hands tied.
4. Yes, let's use 8 bits for API-KEY + version to keep it simple.

With regards to versioning, as long as there is no exponential combination of name + version + sub-name + sub-version, I'm for enumerating them.
We can create APIs on top to make record construction easier.
And the decode result can be translated to nicer representation after decoding.
e.g. convert record to a `map()`

Making it easier at low level (e.g. merge fields to make a union record, or use `map()`)
will make it harder at higher level when constructing
the requests. e.g. one will have to remember which field should be set for which version
if we have clean records, compiler should check it for us.

**Comment by id** [comment]
Awesome stuff. Thanks for finishing it.
Can't approve since I'm the original author, so just go ahead and merge it.

**Comment by id** [comment]
Approved.

**Comment by zmstone** [comment]
will merge when brod 3.0 development is ready to release.

**Pull request merged**
