### PR TITLE
Generate kpro_schema.erl

### PR DESCRIPTION
**Pull request by zmstone**
Trying out another approach:
Generate field type specs encoder should take proplist or map as input 
and decoder should produce proplist or map as output.

The drawback is that compiler won't help to identify typos in field names
and perhaps a performance degrade when working with proplists.

### CODE REVIEW

**Comment by codesnik** [comment]
@zmstone I'll look into it, thanks. I've seen (but never replicated) some benchmarks online, proplists seem much (~3x) worse than maps when reading, perfomance-wise. But this doesn't matter, probably. This is more about API. And about brod API as well, if kafka_protocol records and types are "leaked" to apps using brod.
Can you point me to some apps using brod heavily? https://github.com/klarna/brucke probably, anything even more representative?

**Comment by zmstone** [comment]
Agree, performance should not be a dominant factor.
To mitigate the typo-prone drawback, we can make the encoder decoder defensive:
do not allow default values, or throw exception when unknown filed name is found.

Brucke does not use kpro records directly.
The only place (that I know of) where kpro data types are directly accessed is kastlex:
https://github.com/klarna/kastlex/blob/1.2.1/lib/kastlex/cg_status_collector.ex#L145

**Comment by id** [comment]
This looks neat. In my opinion we should take one step further and use maps instead of proplists.

**Comment by zmstone** [comment]
The schema has to be prop-list because the fields have order.
I agree we should support maps for DATA i.e. maps as encoder input and decoder output.

**Comment by zmstone** [comment]
included in #21

**Pull request closed without merging**
